name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull abhishekrockzz78/automate_image:latest
    - name: Delete Old docker container
      run: sudo docker rm -f automate_image-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 5011:5011 --name automate_image-container abhishekrockzz78/automate_image