# dckr_pat_sc98uPUmK61qOX9-_0u3vOpgd2Q
name: Build and push Docker image to Docker Hub
on: push
jobs:
  push_to_registry:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - name: check out the repo
          uses: actions/checkout@v2

        - name: login to Docker Hub
          uses: actions/login-actions@v2

          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN    }}

        - name: Build and push docker image
          uses: docker/docker-push-action@v2
          with:
            context: Dockerfile
            push: true
            tags: abhishek123456780/automate_image:latest     